# Generated by Django 4.1.7 on 2023-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_human_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы'),
        ),
    ]
