# Generated by Django 4.1.7 on 2023-03-31 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hobby_human_photo_human_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('photo', models.ImageField(upload_to='authors_photos', verbose_name='Фото')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('image', models.ImageField(upload_to='services_images/', verbose_name='Картинка')),
                ('price', ckeditor.fields.RichTextField(verbose_name='Прайслист')),
                ('author', models.ManyToManyField(to='main.developer', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='services',
            field=models.ManyToManyField(to='main.service', verbose_name='Услуги'),
        ),
    ]
