# Generated by Django 4.1.7 on 2023-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_developer_service_developer_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='main.developer', verbose_name='Автор'),
        ),
    ]
