# Generated by Django 4.1.7 on 2023-03-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_alter_human_age_alter_human_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
