# Generated by Django 4.1.7 on 2023-03-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_alter_human_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Хобби',
                'verbose_name_plural': 'Увлечения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='human',
            name='photo',
            field=models.ImageField(null=True, upload_to='services/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='human',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_pages.hobby'),
        ),
    ]
